Repository ChristofferTan/csc207-project, pull requests merged in 2023-12, with the labels that each got.

#49 Improved MealType Logic, Consistent UserFactory Calls in tests, and Comprehensive GenerateRecipeTest
  src/entity/MealType.java
  test/entity/MealTypeTest.java
  test/interface_adapters/generate_recipe/GenerateRecipeTest.java
  test/use_case/add_favorite_recipe/AddFavoriteRecipeInteractorTest.java
  test/use_case/add_friend/AddFriendInteractorTest.java
  test/use_case/after_generated_recipe/AfterGeneratedRecipeTest.java
  test/use_case/delete_favorite_recipe/DeleteFavoriteRecipeInteractorTest.java
  test/use_case/edit_profile/EditProfileInteractorTest.java
  test/use_case/login/LoginInteractorTest.java
  test/use_case/my_favorite_recipe/MyFavoriteRecipeInteractorTest.java
  test/use_case/myprofile/MyProfileInteractorTest.java
Labels: enhancement, test

#54 Fixed some bugs about planner
  src/data_access/FilePlannerDataAccessObject.java
  src/data_access/FileRecipeDataAccessObject.java
  src/interface_adapters/after_generated_recipe/AfterGeneratedRecipeViewModel.java
  src/interface_adapters/generate_recipe/GenerateRecipeViewModel.java
  src/interface_adapters/my_favorite_recipe/MyFavoriteRecipeViewModel.java
Labels: bug

#55 Fixed the bug with calorie tracker, now it is displayed correctly.
  src/data_access/FilePlannerDataAccessObject.java
  src/interface_adapters/my_planner/MyPlannerPresenter.java
  src/use_case/calorie_tracker/CalorieTrackerInteractor.java
Labels: bug

#56 Fixed some bugs where the height and weight are flipped when creating a new account.
  src/entity/CommonUser.java
Labels: bug

#59 Some changes and bug fixes for calorie tracker (in planner), documentation for DAO and api methods
  src/api/edamam/GenerateRecipeAPICaller.java
  src/data_access/FilePlannerDataAccessObject.java
  src/data_access/FileRecipeDataAccessObject.java
  src/data_access/FileUserDataAccessObject.java
  src/interface_adapters/calorie_tracker/CalorieTrackerPresenter.java
  src/interface_adapters/generate_recipe/GenerateRecipeViewModel.java
  src/interface_adapters/my_planner/MyPlannerState.java
  src/use_case/calorie_tracker/CalorieTrackerInteractor.java
  src/use_case/calorie_tracker/CalorieTrackerOutputData.java
  src/view/AfterGeneratedRecipeView.java
  src/view/MyPlannerView.java
  test/use_case/calorie_tracker/CalorieTrackerInteractorTest.java
Labels: bug, documentation, enhancement

#60 Added test cases for MainTest.java and SignupViewTest.java
  test/app/MainTest.java
  test/view/SignupViewTest.java
Labels: test

#62 Refactor: Apply dependency injection for API and file storage and rename file
  src/api/edamam/GenerateRecipeAPICaller.java
  src/api/file/io/FileIOFacade.java
  src/data_access/FilePlannerDataAccessObject.java
  src/data_access/FileRecipeDataAccessObject.java
  src/data_access/FileUserDataAccessObject.java
  src/data_access/OnlineFileStorageManager.java
  src/use_case/generate_recipe/GenerateRecipeAPICallerInterface.java
  src/use_case/generate_recipe/GenerateRecipeInteractor.java
  test/api/file/io/FileIOTest.java
  test/data_access/FileDataAccessObjectTest.java
  test/interface_adapters/generate_recipe/GenerateRecipeTest.java
  test/view/SaveRecipeTest.java
Labels: enhancement
